#!/bin/bash

if [ "${BASH_SOURCE[0]}" == "${0}" ];
then
    echo
    echo "This script must be sourced"
    echo
    exit
fi

__conda_setup="$('/Users/rmodrak/packages/miniconda2/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/rmodrak/packages/miniconda2/etc/profile.d/conda.sh" ]; then
        . "/Users/rmodrak/packages/miniconda2/etc/profile.d/conda.sh"
    else
        export PATH="/Users/rmodrak/packages/miniconda2/bin:$PATH"
    fi
fi
unset __conda_setup

