#!/bin/bash

if [ "${BASH_SOURCE[0]}" == "${0}" ];
then
    echo \
"
This script must be sourced
"
    exit
fi

CONDA3="$HOME/packages/miniconda3"
conda deactivate
remove-path "$CONDA3/bin"
remove-path "$CONDA3/condabin"

