#!/bin/bash

if [ "${BASH_SOURCE[0]}" == "${0}" ];
then
    echo \
"
This script must be sourced
"
    exit
fi

CONDA2="$HOME/packages/miniconda2"
conda deactivate
remove-path "$CONDA2/bin"
remove-path "$CONDA2/condabin"

