#!/bin/bash -e


ENV="mtuq"
SRC="$HOME/devel/mtuq"

ORIGIN="https://github.com/rmodrak/mtuq.git"
UPSTREAM="https://github.com/uafgeotools/mtuq.git"

CONDA="$HOME/virtual/miniconda3"
PYGMT='pygmt>=0.9'


if ! type conda > /dev/null; then
    echo "conda not found. Exiting..."
    exit
fi


source "$CONDA/etc/profile.d/conda.sh"
conda config --prepend channels conda-forge
conda create --name $ENV python=3
conda activate $ENV


if [ -e $SRC ]; then
    echo "Repository exists: $SRC"
    cd $SRC

else
    echo "Cloning: $ORIGIN"
    git clone $ORIGIN $SRC
    cd $SRC
    git remote add upstream $UPSTREAM

fi


pip install --upgrade pip
conda env update --name $ENV --file env.yaml
conda install $PYGMT

./data/examples/unpack.bash
./data/tests/unpack.bash

find $CONDA/envs/mtuq/ -name matplotlibrc -exec sed -i '' \
    's/backend: macosx/backend: Agg/' {} +

