#!/bin/bash -e


ENV="mtbench"
SRC="$HOME/packages/mtuq"
CONDA="$HOME/packages/miniconda3"


if ! type conda > /dev/null; then
    echo "conda not found. Exiting..."
    exit
fi


source "$CONDA/etc/profile.d/conda.sh"
conda config --prepend channels conda-forge
conda create --name $ENV python=3.6
conda activate $ENV


if [ -e $SRC ]; then
    cd $SRC

else
    echo "Not found: $SRC"
    exit -1

fi


conda install numpy 
conda install gmt=6.0.0
pip install instaseis
pip install mpi4py
pip install -e .


echo "
TO FINISH INSTALLATION, NAVIGATE TO MTBENCH DIRECTORY AND TYPE

conda activate $ENV
pip install -e .
"
